### ISSUE TITLE
config.yml does not exist anymore

### ISSUE THREAD

**Issue by flobaader** [gshipley/installcentos#10]
There is no file `playbooks/byo/config.yaml` anymore.
Is `playbooks/deploy_cluster.yml` the right one?

**Comment by waydenie** [comment]
I found that I had to 'git checkout release-3.7' branch of the openshift-ansible repo, rather than master, for playbooks/byo/config.yaml ... deploy_cluster.yml wouldn't run for me...

(I'm not sure this was the correct solution, but it appears to have worked for me, so far... )

The other issues I had were dependency related, maybe because I was using RHEL7.4 instead of CentOS? I found that I needed Ansible v2.4.2 ,  python-passlib and java-1.8.0-openjdk-headless from the RHEL repos, in addition to the ones listed in Grant's great repo and video(s) ! :-)
