### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by javabeanz** [gshipley/installcentos#116]
during installation i get :
.....
skipping: [192.168.188.28]

TASK [openshift_control_plane : Wait for control plane pods to appear] *********
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (59 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (58 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (57 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (56 retries left).
FAILED - RETRYING: Wait for c....
etc.
....

Ho can i fix this ?

**Comment by ryannix123** [comment]
@javabeanz I'm seeing these errors as well, but only on one system, which is older but still meets the recommended specs for deployment.

**Comment by marekjelen** [comment]
this is usually caused by using Ansible 2.7

**Comment by javabeanz** [comment]
also see https://github.com/gshipley/installcentos/issues/107

**Comment by javabeanz** [comment]
fix is ready in pull request

**Comment by marekjelen** [comment]
Closed and commented on the pull-request @javabeanz

**Comment by hisanoster** [comment]
Is this fixed? I am still having the same issue as of this afternoon...

**Comment by javabeanz** [comment]
@hisanoster you can alter the ansible version in the installation script from 2.6.x to 2.7.1.1 as a temporary workaround. let me know if this works for you.

**Comment by marekjelen** [comment]
@hisanoster hey ... are you running 2.6 Ansible? Can you share more info on what's failing?

**Comment by vrutkovs** [comment]
Please avoid using 2.7.0 - its known to be broken. There is no 2.7.1 RPM yet, so we can't stick to it. There has been some reports that it works well (an issue with var inheritance was fixed there).

ansible 2.6.5 should work fine, its the version we use in CI currently, so if you encounter an error with it please file an issue in https://github.com/openshift/openshift-ansible with inventory and `-vvv` level logs

**Comment by hisanoster** [comment]
I was running 2.7 earlier but now I am running 2.6.5, both of which shows the same results as follows.

FAILED - RETRYING: Wait for control plane pods to appear (9 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (8 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (7 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (6 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (5 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (4 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (3 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (2 retries left).
FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
failed: [10.25.75.202] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-ctrl.elab.local -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "Unable to connect to the server: Service Unavailable\n", "stdout": ""}}
++++

error: unable to recognize "oc_vol.yaml": Get https://ctrl.elab.local:8443/api?timeout=32s: Service Unavailable
created volume 29
error: unable to recognize "oc_vol.yaml": Get https://ctrl.elab.local:8443/api?timeout=32s: Service Unavailable
created volume 30
^C
[root@ctrl installcentos]# ansible --version
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@ctrl installcentos]# 

Should I be running 2.6 or 2.7?

**Comment by ryannix123** [comment]
@javabeanz said Ansible 2.7.1.1 worked, although this version is not supported.

**Comment by vrutkovs** [comment]
2.7.1.1 is not supported as we can't verify it works in CI first. Once CentOS would update the repos we'll check if it passes the test and start supporting it eventually.

`Wait for control plane pods to appear` is not related to ansible versions. Please check that container with `ctrl.elab.local` was created. If it wasn't, it means the hostname is not expected (see #120) - you might need to adjust your hostname to be equal to `hostname -f`

**Comment by hisanoster** [comment]
No change in the results with 2.7.1.1.
With regards to the hostname, both hostname and hostname -f returns the same value.

**Comment by hisanoster** [comment]
> 2.7.1.1 is not supported as we can't verify it works in CI first. Once CentOS would update the repos we'll check if it passes the test and start supporting it eventually.
> 
> `Wait for control plane pods to appear` is not related to ansible versions. Please check that container with `ctrl.elab.local` was created. If it wasn't, it means the hostname is not expected (see #120) - you might need to adjust your hostname to be equal to `hostname -f`

How do I check whether the container with ctrl.elab.local was created by the way?

**Comment by marekjelen** [comment]
@hisanoster @vrutkovs the errors above with the ctrl.elab.local seems to come from creating the PVs, but the cluster failed to provision, so it's failing

https://github.com/gshipley/installcentos/blob/master/install-openshift.sh#L163-L180

**Comment by vrutkovs** [comment]
>How do I check whether the container with ctrl.elab.local was created by the way?

Check `docker ps -a` output

**Comment by hisanoster** [comment]
the container is not created..

**Comment by hisanoster** [comment]
> @hisanoster @vrutkovs the errors above with the ctrl.elab.local seems to come from creating the PVs, but the cluster failed to provision, so it's failing
> 
> https://github.com/gshipley/installcentos/blob/master/install-openshift.sh#L163-L180

right, any idea why it is?

**Comment by hisanoster** [comment]
I guess the pod creation being failing is visible here...
Anyone any clue here??

FAILED - RETRYING: Wait for control plane pods to appear (1 retries left).
failed: [10.25.75.207] (item=etcd) => {"attempts": 60, "changed": false, "item": "etcd", "msg": {"cmd": "/usr/bin/oc get pod master-etcd-ctrl.elab.local -o json -n kube-system", "results": [{}], "returncode": 1, "stderr": "Unable to connect to the server: Service Unavailable\n", "stdout": ""}}
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).

**Comment by vrutkovs** [comment]
>Unable to connect to the server: Service Unavailable
API server didn't come up

>the container is not created..

there are no containers in the output? Must be kubelet stuck on something. What's in `origin-node.service` logs?

**Comment by hisanoster** [comment]
Some change.. when I ran the following script the containers got created:

3. Run the automagic installation script as root with the environment variable in place:
curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh | INTERACTIVE=false /bin/bash

Here is what's in origin-node.service:

[root@ctrl installcentos]# systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-11-09 15:52:22 EST; 1h 46min ago
     Docs: https://github.com/openshift/origin
 Main PID: 15984 (hyperkube)
   CGroup: /system.slice/origin-node.service
           └─15984 /usr/bin/hyperkube kubelet --v=2 --address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-token-w...

Nov 09 17:38:09 ctrl.elab.local origin-node[15984]: W1109 17:38:09.438276   15984 cni.go:172] Unable to update cni config: No network...i/net.d
Nov 09 17:38:09 ctrl.elab.local origin-node[15984]: E1109 17:38:09.438434   15984 kubelet.go:2101] Container runtime network not read...ialized
Nov 09 17:38:10 ctrl.elab.local origin-node[15984]: E1109 17:38:10.685742   15984 summary.go:102] Failed to get system container stats for "...
Nov 09 17:38:10 ctrl.elab.local origin-node[15984]: E1109 17:38:10.685771   15984 summary.go:102] Failed to get system container stat...ervice"
Nov 09 17:38:14 ctrl.elab.local origin-node[15984]: W1109 17:38:14.439338   15984 cni.go:172] Unable to update cni config: No network...i/net.d
Nov 09 17:38:14 ctrl.elab.local origin-node[15984]: E1109 17:38:14.439471   15984 kubelet.go:2101] Container runtime network not read...ialized
Nov 09 17:38:19 ctrl.elab.local origin-node[15984]: W1109 17:38:19.440503   15984 cni.go:172] Unable to update cni config: No network...i/net.d
Nov 09 17:38:19 ctrl.elab.local origin-node[15984]: E1109 17:38:19.440644   15984 kubelet.go:2101] Container runtime network not read...ialized
Nov 09 17:38:20 ctrl.elab.local origin-node[15984]: E1109 17:38:20.696344   15984 summary.go:102] Failed to get system container stats for "...
Nov 09 17:38:20 ctrl.elab.local origin-node[15984]: E1109 17:38:20.696385   15984 summary.go:102] Failed to get system container stat...ervice"
Hint: Some lines were ellipsized, use -l to show in full.
[root@ctrl installcentos]# ^C
[root@ctrl installcentos]#

**Comment by vrutkovs** [comment]
`status` is good, but we need `journalctl -lu origin-node`.

In any case, this is should be converted into an openshift-ansible playbook really

**Comment by hisanoster** [comment]
journalctl -lu origin-node produces a lot of logs.. 
[os_1109.log](https://github.com/gshipley/installcentos/files/2567743/os_1109.log)

**Comment by vrutkovs** [comment]
It seems you do have the API running there, there are 6 containers running there

**Comment by hisanoster** [comment]
seems that way but all those control plane pods do not appear to be accessible..
what else can i check/try...?
