### ISSUE TITLE
Openshift Excluder Failed to Install

### ISSUE THREAD

**Issue by jcperezamin** [gshipley/installcentos#4]
TASK [openshift_excluder : Install openshift excluder] *************************
fatal: [console.techdope.io]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'origin-excluder-1.4.0*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-excluder-1.4.0*' found available, installed or updated"]}

**Comment by mingxhzhu** [comment]
I was able to bypass that error by adding "enable_docker_excluder=false" and "enable_excluders=false" to the inventory file. But now I am stuck with the error: 
TASK [openshift_hosted : create the default registry service] ******************
fatal: [console.]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/usr/local/bin/oc get service docker-registry -o json -n default", "results": [{}], "returncode": 1, "stderr": "Unable to connect to the server: net/http: TLS handshake timeout\n", "stdout": ""}}

**Comment by sivadatla** [comment]
You need place the following lines in inventory.erb file:
`enable_docker_excluder=false
enable_openshift_excluder=false`

You also need to downgrade ansible from 2.2.1 to 2.2.0

**Comment by jcperezamin** [comment]
Finally, It works! but with the new ansible version 2.3 :-)

**Comment by deltaospoc** [comment]
@gshipley, you are awesome. Origin 1.4 installation tutorial fantastic. I did .... It works for me..  !!!

We are expecting Origin 3.7 video tutorial. Because so many stuffs are changed in the Openshift Origin 3.7 

@sivadatla and @jcperezamin you both guys are help me lot to finish my installation.

But I have to install Origin 3.7 to deploy the Java application Tomcat. Can you please me guide step by step method for that.

Questions:
1. What Ansible version I have to use?
2. What Openshift Ansible Version I have to use?
3. What are the packages I have to install
4. Please guide, error free Inventory file for Origin 3.7

Please guide me...

**Comment by jcperezamin** [comment]
When I finally have got some free time to test Origin 3.7. Someone delete the config.yml from the master 
[root@new-host-2 ~]# ansible-playbook -i inventory ./openshift-ansible/playbooks/byo/config.yml
ERROR! the playbook: ./openshift-ansible/playbooks/byo/config.yml could not be found
