### ISSUE TITLE
Patching the single cluster?

### ISSUE THREAD

**Issue by ryannix123** [gshipley/installcentos#61]
@marekjelen  @jcrossley3

I'm not sure how to apply this patch to run OpenWhisk on OpenShift. https://github.com/projectodd/openwhisk-openshift

minishift openshift config set --patch \
    '{"admissionConfig":
        {"pluginConfig":
            {"openshift.io/ImagePolicy":
                {"configuration":
                    {"apiVersion": "v1",
                     "kind": "ImagePolicyConfig",
                     "resolveImages": "AttemptRewrite"}}}}}'

**Comment by marekjelen** [comment]
@jorgemoralespou can you help here? I am not as familiar with `minishift`.

**Comment by jorgemoralespou** [comment]
@ryannix123 If I understand what you're trying to do, is execute the addon on the OpenShift cluster that has been installed via this repository method?

If that is correct, you should get into the OpenShift VM and execute that command without "minishift" prefix, but AFAIK that is not required on a regular cluster but only on a minishift cluster, because how that OpenShift instance is configured by default.

If what you want is help setting up OpenWhisk on minishift, the openwisk addon is a great place to start and ask there, although I guess you're coming from that (https://github.com/minishift/minishift-addons/tree/master/add-ons/openwhisk).

If you give me more details on what you're trying to do I might be able to provide a better answer.

**Comment by ryannix123** [comment]
What is the syntax for patching? Something like this?

`oc patch config set --patch '{"admissionConfig": "pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"apiVersion": "v1","kind": "ImagePolicyConfig", "resolveImages": "AttemptRewrite"}}}}}' `

**Comment by jorgemoralespou** [comment]
oc is the cli for OpenShift. On the server there is another command, called openshift (soon to be removed) that is admin CLI, but the command patch is removed from that CLI.

Currently the options for a 3.9 environment are:
- Use sed
- Use a docker image of openshift:3.7 (or before) to patch the config file, like this:

```
docker run -v <CONF_DIR>:/config -it --rm \
       openshift/origin:v3.7 \
       /usr/bin/openshift ex config patch /tmp/master-config.yml --patch='{"admissionConfig": "pluginConfig": {"openshift.io/ImagePolicy": {"configuration": {"apiVersion": "v1","kind": "ImagePolicyConfig", "resolveImages": "AttemptRewrite"}}}}}'
```

Replace CONF_DIR with your directory. 

Anyways, you need to verify that is the config you need in your 3.9 OpenShift instance. You should ask in the appropriate forum, and not here.

**Comment by jcrossley3** [comment]
@ryannix123 fwiw, you shouldn't need to do this anymore as we reverted our ImageStream use on the master branch. (it's still good to know how, of course)
