### ISSUE TITLE
openshift services are not getting started

### ISSUE THREAD

**Issue by amitn16** [gshipley/installcentos#77]
Hi,
I am getting following error message after completion of ./install-openshift.sh.  my environment is single host centos7 running as VM in KVM.  please help
> 

To view or setup config directly use the 'config' command.
created volume 199
chcon: can't apply partial context to unlabeled file ‘/mnt/data/vol200’
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
created volume 200
******
* Your console is https://console.bruttech.com:8443
* Your username is admin
* Your password is admin123
*
* Login using:
*
$ oc login -u admin -p admin123 https://console.bruttech.com:8443/
******
error: dial tcp 192.168.1.168:8443: getsockopt: connection refused - verify you have provided the correct host and port and that the server is currently running.

>

**Comment by TeamForrest** [comment]
I am having the same problem. Has anyone been able to solve this one?

**Comment by marekjelen** [comment]
This seems like the IP address does not correspond with the domain name.

**Comment by marekjelen** [comment]
Please reopen in case the problem persists.

**Comment by victorroeder** [comment]
Hi amitn16,

I had the same issue and it figured out it was caused by the disabled SELinux.
Please check by running sestatus or checking your /etc/sysconfig/selinux (entry SELINUX=disabled). Set it to "permissive", then reboot. Then grep /var/log/messages for any "SELinux is preventing" entries. If nothing is found, you *can* consider to set it to "enforced". But this option prevented my vserver to boot up again. So be careful! In my case SELINUX=premissive was already enough for the Openshift installation and solved my problems.

Bye,
Victor
